# Generated by Django 4.1.7 on 2023-03-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Brads_Logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='Brand_Address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='Brand_City',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='Brand_Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='Brand_State',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='Brand_Zip',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
