# Generated by Django 4.1.7 on 2023-03-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brand_brads_logo_brand_brand_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Brand_Password',
            field=models.IntegerField(null=True),
        ),
    ]
