# Generated by Django 4.1.7 on 2023-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_brand_brads_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Brads_Logo',
            field=models.ImageField(null=True, upload_to='media/Brands_Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='Brand_Password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
