# Generated by Django 4.1.7 on 2023-03-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_brand_brads_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Brads_Logo',
            new_name='Brands_Logo',
        ),
    ]
