# Generated by Django 4.1.7 on 2023-03-25 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_brads_logo_brand_brands_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=40)),
                ('Product_Price', models.CharField(max_length=20)),
                ('Product_Category', models.CharField(max_length=20)),
                ('Product_Description', models.TextField(max_length=50)),
                ('Product_Image', models.ImageField(upload_to='Product_Images/')),
                ('Product_Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
            ],
        ),
    ]
