# Generated by Django 4.1.7 on 2023-03-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Image',
        ),
        migrations.CreateModel(
            name='PImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(upload_to='Product_Images/')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
