# Generated by Django 4.1.7 on 2023-03-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Stock',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
