# Generated by Django 4.1.7 on 2023-03-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_product_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Stock',
            field=models.IntegerField(default=0),
        ),
    ]
