# Generated by Django 4.1.7 on 2023-04-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemPrice', models.CharField(max_length=20)),
                ('ItemQuantity', models.IntegerField(default=1, max_length=100)),
                ('BrandOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
                ('CustomerOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('ProductOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderitem')),
            ],
        ),
    ]
